// wit is only kebab-case
package hello:host;

world init {

  export flush-to-vfs: func();
  
  export flush-from-vfs: func();
  export input-char: func(c: u32);
  export interrupt: func();
  export init: func();
  export main: func();
}
