// wit is only kebab-case
package hello:host;

world init {
  variant command-request {
    handled,
    download(string),
    exec-file(tuple<string, list<string>>),
    not-found(string),
  }

  export flush-to-vfs: func();
  
  export flush-from-vfs: func();
  
  export run-command: func(args: list<string>) -> command-request;

  export init: func();
  export main: func();
}
