// wit is only kebab-case
package vfs:host;

interface bridge {
  resource downloader {
    download-file-start: static func(name-ptr: s32, name-len: s32);
    download-file-chunk: static func(data-ptr: s32, data-len: s32);
    download-file-end: static func();

    sysroot-start-fetch: static func(triple-ptr: s32, triple-len: s32);
    sysroot-get-next-file-meta: static func(name-len-ptr: s32, data-len-ptr: s32) -> s32;
    sysroot-read-file-name: static func(name-ptr: s32);
    sysroot-read-file-chunk: static func(data-ptr: s32, chunk-len: s32);
  }

  resource terminal {
    terminal-write: static func(session-id: u32, data-ptr: s32, data-len: s32);
  }

  resource lsp {
    host-run-cargo: static func(req-ptr: s32, req-len: s32, out-stdout-ptr: s32, out-stdout-len: s32, out-stderr-ptr: s32, out-stderr-len: s32, out-status: s32) -> s32;
    host-free-memory: static func(ptr: s32, len: s32);
  }

  resource http {
    request-start: static func(method-ptr: s32, method-len: s32, url-ptr: s32, url-len: s32, headers-ptr: s32, headers-len: s32, body-ptr: s32, body-len: s32, out-request-id: s32, out-status: s32, out-headers-len: s32, out-body-len: s32, out-error-len: s32) -> s32;
    response-read-headers: static func(request-id: u32, data-ptr: s32, data-len: s32) -> s32;
    response-read-body: static func(request-id: u32, data-ptr: s32, data-len: s32) -> s32;
    response-read-error: static func(request-id: u32, data-ptr: s32, data-len: s32) -> s32;
    response-end: static func(request-id: u32) -> s32;
  }

  resource child-process {
    request-start: static func(argv-ptr: s32, argv-len: s32, env-ptr: s32, env-len: s32, module-len: s32, out-request-id: s32) -> s32;
    request-write: static func(request-id: u32, data-ptr: s32, data-len: s32) -> s32;
    request-run: static func(request-id: u32, out-status: s32, out-error-len: s32) -> s32;
    request-read-error: static func(request-id: u32, data-ptr: s32, data-len: s32) -> s32;
    request-recover: static func(out-request-id: s32, out-state: s32, out-status: s32, out-error-len: s32) -> s32;
    request-end: static func(request-id: u32) -> s32;
  }
}

world vfs-host {
  import bridge;

  export flush-to-vfs: func();

  export flush-from-vfs: func();
  export dispatch: func(session-id: u32, event-type: u32, arg1: u32, arg2: u32);
  export alloc-buf: func(len: u32) -> u32;
  export free-buf: func(ptr: u32, len: u32);
  export debug-set-terminal-capture: func(enabled: bool);
  export debug-terminal-output-len: func() -> u32;
  export debug-read-terminal-output: func(ptr: u32, len: u32) -> u32;
  export init: func();
  export main: func();
}
